#include <iostream>
#include <vector>

using namespace std;


int main()
{
	vector <int> Number = { 1,2,3,4,5 };

	try
	{
		cout << Number.at(5);

	}
	catch(...)
	{

		cout << "Yes ! no exceptions \n";
	}
	
	return 0;
}
